version: "3.8"

services:
  # Service untuk aplikasi Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    # Hanya mount file .env, storage dan database akan diatur di dalam image
    volumes:
      - ./.env:/var/www/html/.env

  # Service untuk web server Nginx
  webserver:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      # Mount seluruh folder proyek untuk Nginx
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
