version: "3.8"

services:
  # Service untuk aplikasi Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      # Mount hanya file .env, bukan seluruh folder proyek
      - ./.env:/var/www/html/.env
      # Tambahkan kembali volume untuk database SQLite agar data persisten
      - db-data:/var/www/html/database

  # Service untuk web server Nginx
  webserver:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      # Mount seluruh folder proyek untuk Nginx
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db-data: {}
