version: "3.8"

services:
  # Service untuk aplikasi Laravel
  app:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      # Mount hanya file .env, bukan seluruh folder proyek
      - ./.env:/var/www/html/.env

  # Service untuk web server Nginx
  webserver:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db-data: {} # Mendefinisikan volume untuk database SQLite
