version: "3.8"

services:
  # Service untuk aplikasi Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      # Volume untuk database SQLite dan direktori storage
      - db-data:/var/www/html/database
      - ./storage:/var/www/html/storage

  # Service untuk web server Nginx
  webserver:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db-data: {}
